
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "iris_utils"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
  "tqdm",
  "scitools-iris"
]


